name: "Transmute GitHub JSON-LD Action"
description: |
  This action enables JSON-LD operations within GitHub Workflows.
inputs:
  operation:
    description: |
      A JSON-LD Operation.
    require: true
  document:
    description: |
      A JSON Document (string).
    require: true

outputs:
  json:
    description: "The output as json."

runs:
  using: "node16"
  main: "dist/index.js"
