name: CI

on: [push, workflow_dispatch]

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Coverage
        run: npm run coverage
      - name: Build
        run: npm run build
      - name: Badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
  frame:
    needs:
      - coverage
    runs-on: ubuntu-latest
    name: Frame
    outputs:
      json: ${{ steps.frame.outputs.json }}
    steps:
      - name: JSON-LD Frame
        uses: ./ # Use a "private unpublished github action in the current repository"
        id: frame
        with:
          operation: frame
          document: |
            {
              "http://schema.org/name": "Orie Steele",
              "http://schema.org/url": {"@id": "https://transmute.industries"}
            }
      - name: Review the frame
        run: |-
          echo '${{ steps.frame.outputs.json }}' >> framed.json
      - name: Upload the work as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: recent-frame
          path: framed.json
          
  

    
    